/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BrightonMuseums (https://sketchfab.com/BrightonMuseums)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/venus-of-willendorf-1f4c2a6a199e438da675ffaac15849c9
title: Venus of Willendorf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/venus.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.035}>
        <group position={[1.02, -38.61, -6.92]} rotation={[1.58, 0, -0.07]}>
          <group position={[-21.81, -71.26, -47.45]}>
            <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
            <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
            <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
            <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
            <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
            <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
            <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
            <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/venus.gltf')
